Add VIP in Baremetal Cluster
Nordix/cluster-api-provider-baremetal pull request #10
Opened 2019-10-14 11:05 UTC by kashifest

Added virtual IP functionality in baremetal cluster manager

Co-authored-by: Xenwar <anwar.hassen@est.tech>

Signed-off-by: kashifest <kashif.khan@est.tech>

2019-10-16 04:59 UTC, Jaakko-Os commented on api/v1alpha2/baremetalcluster_types.go
> +	APIEndpoint string `json:"apiEndpoint,omitempty"`
BareMetalClusterStatus struct already contains APIEndpoints list, why not use it?
The BareMetalClusterSpec comment also implies the struct content.

2019-10-16 05:02 UTC, Jaakko-Os commented on baremetal/cluster_manager.go
> +			Port: port,
when using BareMetalClusterStatus struct as it is, host and port could be:

			Host: s.Cluster.Status.APIEndpoints[0].Host,
			Port: s.Cluster.Status.APIEndpoints[0].Port,

2019-10-16 05:05 UTC, Jaakko-Os requested changes
BareMetalClusterStatus struct already contains APIEndpoints list, why not use it

2019-10-17 07:18 UTC, maelk requested changes
Can you please split this in two ? the first PR for the apiendpoint handling, the second PR for the controlplane.yaml modifications so that it is easy to revert when we have a proper load-balancing solution in place (and do the modifications for the two other control plane nodes)

2019-10-17 07:18 UTC, maelk commented on examples/controlplane/controlplane.yaml
> +        }
This is also needed in the two other control planes

2019-10-17 07:18 UTC, maelk commented on baremetal/cluster_manager.go
> +	endPoint := s.BareMetalCluster.Spec.APIEndpoint
what if endpoint is empty ? Maybe remove omitempty in the struct definition ?

2019-10-17 07:19 UTC, maelk commented
> BareMetalClusterStatus struct already contains APIEndpoints list, why not use it

they are using it for the status, but we need also to give it as a spec

2019-10-18 09:12 UTC, merged